"""Curated concept families (ground-truth geometry) for Gemma-7b extraction.

Each family maps to an EXISTING template in prompt_templates.py and carries the
expected topology from the research ground-truth list.  Values are ordered so a
sequential color map traces the expected manifold coordinate where one exists.
"""

# ruff: noqa: E402  (sys.path setup must precede sibling imports)

FAMILIES = [
    # name, template, expected topology (short), ordered values
    {
        "name": "years",
        "template": "year",
        "expected": "1D line (ordered)",
        "values": [
            "1500",
            "1550",
            "1600",
            "1650",
            "1700",
            "1750",
            "1800",
            "1850",
            "1900",
            "1950",
            "2000",
        ],
    },
    {
        "name": "quantities",
        "template": "quantity",
        "expected": "1D log line",
        "values": ["1", "10", "100", "1000", "10000", "100000", "1000000"],
    },
    {
        "name": "colors",
        "template": "color",
        "expected": "hue circle (S1)",
        "values": [
            "red",
            "orange",
            "yellow",
            "lime",
            "green",
            "teal",
            "cyan",
            "blue",
            "indigo",
            "violet",
            "magenta",
            "pink",
        ],
    },
    {
        "name": "emotions",
        "template": "emotion",
        "expected": "circumplex (S1)",
        "values": [
            "excited",
            "happy",
            "content",
            "relaxed",
            "calm",
            "sleepy",
            "bored",
            "depressed",
            "sad",
            "distressed",
            "afraid",
            "angry",
        ],
    },
    {
        "name": "musical_notes",
        "template": "musical_note",
        "expected": "chromatic circle (S1)",
        "values": ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"],
    },
    {
        "name": "circle_of_fifths",
        "template": "musical_key",
        "expected": "circle of fifths (S1)",
        "values": ["C", "G", "D", "A", "E", "B", "F#", "Db", "Ab", "Eb", "Bb", "F"],
    },
    {
        "name": "clock_hours",
        "template": "hour",
        "expected": "clock circle (S1)",
        "values": [
            "1:00",
            "2:00",
            "3:00",
            "4:00",
            "5:00",
            "6:00",
            "7:00",
            "8:00",
            "9:00",
            "10:00",
            "11:00",
            "12:00",
        ],
    },
    {
        "name": "compass",
        "template": "compass_direction",
        "expected": "bearing circle (S1)",
        "values": [
            "North",
            "Northeast",
            "East",
            "Southeast",
            "South",
            "Southwest",
            "West",
            "Northwest",
        ],
    },
    {
        "name": "seasons",
        "template": "season",
        "expected": "annual circle (S1)",
        "values": ["Spring", "Summer", "Autumn", "Winter"],
    },
    {
        "name": "planets",
        "template": "planet",
        "expected": "1D ordered / log line",
        "values": [
            "Mercury",
            "Venus",
            "Earth",
            "Mars",
            "Jupiter",
            "Saturn",
            "Uranus",
            "Neptune",
        ],
    },
    {
        "name": "elements",
        "template": "chemical_element",
        "expected": "periodic spiral",
        "values": [
            "Hydrogen",
            "Helium",
            "Lithium",
            "Beryllium",
            "Boron",
            "Carbon",
            "Nitrogen",
            "Oxygen",
            "Fluorine",
            "Neon",
            "Sodium",
            "Magnesium",
            "Aluminum",
            "Silicon",
            "Phosphorus",
            "Sulfur",
            "Chlorine",
            "Argon",
            "Potassium",
            "Calcium",
        ],
    },
    {
        "name": "amino_acids",
        "template": "amino_acid",
        "expected": "2D property plane",
        "values": [
            "Glycine",
            "Alanine",
            "Valine",
            "Leucine",
            "Isoleucine",
            "Proline",
            "Phenylalanine",
            "Tryptophan",
            "Methionine",
            "Serine",
            "Threonine",
            "Cysteine",
            "Tyrosine",
            "Asparagine",
            "Glutamine",
            "Aspartate",
            "Glutamate",
            "Lysine",
            "Arginine",
            "Histidine",
        ],
    },
    {
        "name": "cities_us",
        "template": "city",
        "expected": "2D map plane",
        "values": [
            "Seattle",
            "San Francisco",
            "Los Angeles",
            "Denver",
            "Phoenix",
            "Houston",
            "Chicago",
            "Atlanta",
            "Miami",
            "Washington",
            "New York",
            "Boston",
        ],
    },
    {
        "name": "cities_global",
        "template": "city",
        "expected": "2D sphere (S2)",
        "values": [
            "Tokyo",
            "Beijing",
            "Mumbai",
            "Cairo",
            "Moscow",
            "London",
            "Cape Town",
            "Buenos Aires",
            "Rio de Janeiro",
            "New York",
            "Honolulu",
            "Sydney",
        ],
    },
    {
        "name": "vowels",
        "template": "vowel_sound",
        "expected": "vowel quadrilateral (2D)",
        "values": ["i", "ɪ", "e", "ɛ", "æ", "a", "ɑ", "ɔ", "o", "ʊ", "u", "ə"],
    },
    {
        "name": "taxonomy",
        "template": "taxonomy_concept",
        "expected": "tree (H0, no loops)",
        "values": [
            "organism",
            "animal",
            "vertebrate",
            "mammal",
            "carnivore",
            "feline",
            "lion",
            "tiger",
            "canine",
            "wolf",
            "dog",
            "primate",
            "human",
            "plant",
            "tree",
            "flower",
        ],
    },
    {
        "name": "kinship",
        "template": "kinship",
        "expected": "tree / relational grid",
        "values": [
            "grandmother",
            "grandfather",
            "mother",
            "father",
            "brother",
            "sister",
            "son",
            "daughter",
            "uncle",
            "aunt",
            "cousin",
            "nephew",
        ],
    },
    {
        "name": "directions_3d",
        "template": "movement_direction",
        "expected": "unit sphere (S2)",
        "values": ["Forward", "Backward", "Left", "Right", "Up", "Down"],
    },
    {
        "name": "chess_pieces",
        "template": "chess_piece",
        "expected": "1D value poset",
        "values": ["Pawn", "Knight", "Bishop", "Rook", "Queen", "King"],
    },
    {
        # Balanced spread of well-known US figures (DW-NOMINATE ground truth).
        "name": "political",
        "template": "political_person",
        "expected": "1D-2D ideology plane",
        "values": [
            "Bernie Sanders",
            "Elizabeth Warren",
            "Barack Obama",
            "Joe Biden",
            "Nancy Pelosi",
            "Mitt Romney",
            "John McCain",
            "Mitch McConnell",
            "Ted Cruz",
            "Ronald Reagan",
        ],
    },
]

# Existing validated sets already extracted (shown in the gallery for context).
EXISTING = [
    {"name": "months_layer_6", "expected": "calendar circle (S1)"},
    {"name": "days_layer_6", "expected": "weekday circle (S1)"},
    {"name": "chess-squares_layer_6", "expected": "8x8 grid (2D)"},
]
