"""Concept sets proposed to extend the corpus from 34 to 68.

PROVENANCE: unlike ``concept_families.FAMILIES``, which came from the original
research ground-truth list, every set here was drafted to fill out the corpus
and none has been reviewed yet.  Each carries the geometry it was chosen to
exemplify, but that expectation is a proposal, not an established result.
Review before any of these enter a reported figure.

Two design rules, both learned from the existing corpus.  Sets have at least
seven values, because a first-harmonic fit on four points is saturated by
construction and ``seasons`` (n=4) scores below its own noise floor.  Values
are ordered so that position in the list traces the expected coordinate, which
is what the cyclic and monotone statistics assume.
"""

# name, family, expected topology (short), ordered values
PROPOSED = [
    # ---------------------------------------------------------------- circles
    {
        "name": "zodiac_signs",
        "family": "circle",
        "expected": "annual zodiac circle (S1)",
        "values": [
            "Aries",
            "Taurus",
            "Gemini",
            "Cancer",
            "Leo",
            "Virgo",
            "Libra",
            "Scorpio",
            "Sagittarius",
            "Capricorn",
            "Aquarius",
            "Pisces",
        ],
    },
    {
        "name": "chinese_zodiac",
        "family": "circle",
        "expected": "twelve-year cycle (S1)",
        "values": [
            "Rat",
            "Ox",
            "Tiger",
            "Rabbit",
            "Dragon",
            "Snake",
            "Horse",
            "Goat",
            "Monkey",
            "Rooster",
            "Dog",
            "Pig",
        ],
    },
    {
        "name": "moon_phases",
        "family": "circle",
        "expected": "lunar cycle (S1)",
        "values": [
            "New Moon",
            "Waxing Crescent",
            "First Quarter",
            "Waxing Gibbous",
            "Full Moon",
            "Waning Gibbous",
            "Last Quarter",
            "Waning Crescent",
        ],
    },
    {
        "name": "clock_minutes",
        "family": "circle",
        "expected": "minute-hand circle (S1)",
        "values": [
            ":00",
            ":05",
            ":10",
            ":15",
            ":20",
            ":25",
            ":30",
            ":35",
            ":40",
            ":45",
            ":50",
            ":55",
        ],
    },
    {
        "name": "compass_16",
        "family": "circle",
        "expected": "sixteen-point bearing circle (S1)",
        "values": [
            "North",
            "North-northeast",
            "Northeast",
            "East-northeast",
            "East",
            "East-southeast",
            "Southeast",
            "South-southeast",
            "South",
            "South-southwest",
            "Southwest",
            "West-southwest",
            "West",
            "West-northwest",
            "Northwest",
            "North-northwest",
        ],
    },
    {
        "name": "bearings_degrees",
        "family": "circle",
        "expected": "bearing circle in degrees (S1)",
        "values": [
            "0 degrees",
            "30 degrees",
            "60 degrees",
            "90 degrees",
            "120 degrees",
            "150 degrees",
            "180 degrees",
            "210 degrees",
            "240 degrees",
            "270 degrees",
            "300 degrees",
            "330 degrees",
        ],
    },
    {
        # Surface-form control: same concepts as `days`, different spelling.
        "name": "weekday_abbreviations",
        "family": "circle",
        "expected": "weekday circle (S1)",
        "values": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    },
    {
        # Surface-form control: same concepts as `months`.
        "name": "month_abbreviations",
        "family": "circle",
        "expected": "calendar circle (S1)",
        "values": [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec",
        ],
    },
    {
        "name": "solfege",
        "family": "circle",
        "expected": "chromatic circle in solfege (S1)",
        "values": [
            "Do",
            "Di",
            "Re",
            "Ri",
            "Mi",
            "Fa",
            "Fi",
            "Sol",
            "Si",
            "La",
            "Li",
            "Ti",
        ],
    },
    {
        "name": "hours_24",
        "family": "circle",
        "expected": "daily circle (S1)",
        "values": [
            "00:00",
            "02:00",
            "04:00",
            "06:00",
            "08:00",
            "10:00",
            "12:00",
            "14:00",
            "16:00",
            "18:00",
            "20:00",
            "22:00",
        ],
    },
    # ------------------------------------------------------------------ lines
    {
        "name": "military_ranks",
        "family": "line",
        "expected": "1D rank order",
        "values": [
            "Private",
            "Corporal",
            "Sergeant",
            "Lieutenant",
            "Captain",
            "Major",
            "Colonel",
            "Brigadier",
            "General",
            "Field Marshal",
        ],
    },
    {
        "name": "education_levels",
        "family": "line",
        "expected": "1D attainment order",
        "values": [
            "preschool",
            "kindergarten",
            "elementary school",
            "middle school",
            "high school",
            "associate degree",
            "bachelor's degree",
            "master's degree",
            "doctorate",
        ],
    },
    {
        "name": "temperature_words",
        "family": "line",
        "expected": "1D intensity scale",
        "values": [
            "frigid",
            "freezing",
            "cold",
            "cool",
            "mild",
            "warm",
            "hot",
            "sweltering",
            "scorching",
        ],
    },
    {
        "name": "size_adjectives",
        "family": "line",
        "expected": "1D magnitude scale",
        "values": [
            "microscopic",
            "tiny",
            "small",
            "little",
            "medium",
            "large",
            "big",
            "huge",
            "gigantic",
        ],
    },
    {
        "name": "frequency_adverbs",
        "family": "line",
        "expected": "1D frequency scale",
        "values": [
            "never",
            "rarely",
            "seldom",
            "occasionally",
            "sometimes",
            "often",
            "usually",
            "always",
        ],
    },
    {
        "name": "probability_words",
        "family": "line",
        "expected": "1D likelihood scale",
        "values": [
            "impossible",
            "improbable",
            "unlikely",
            "doubtful",
            "possible",
            "likely",
            "probable",
            "expected",
            "certain",
        ],
    },
    {
        "name": "mohs_hardness",
        "family": "line",
        "expected": "1D hardness order",
        "values": [
            "Talc",
            "Gypsum",
            "Calcite",
            "Fluorite",
            "Apatite",
            "Orthoclase",
            "Quartz",
            "Topaz",
            "Corundum",
            "Diamond",
        ],
    },
    {
        "name": "decades",
        "family": "line",
        "expected": "1D line (ordered)",
        "values": [
            "1900s",
            "1910s",
            "1920s",
            "1930s",
            "1940s",
            "1950s",
            "1960s",
            "1970s",
            "1980s",
            "1990s",
            "2000s",
            "2010s",
        ],
    },
    {
        "name": "letter_grades",
        "family": "line",
        "expected": "1D grade order",
        "values": ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F"],
    },
    {
        "name": "powers_of_two",
        "family": "line",
        "expected": "1D log line",
        "values": [
            "1",
            "2",
            "4",
            "8",
            "16",
            "32",
            "64",
            "128",
            "256",
            "512",
            "1024",
            "2048",
        ],
    },
    {
        "name": "roman_numerals",
        "family": "line",
        "expected": "1D line (ordered)",
        "values": ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"],
    },
    {
        "name": "beaufort_scale",
        "family": "line",
        "expected": "1D wind-force order",
        "values": [
            "Calm",
            "Light air",
            "Light breeze",
            "Gentle breeze",
            "Moderate breeze",
            "Fresh breeze",
            "Strong breeze",
            "Near gale",
            "Gale",
            "Strong gale",
            "Storm",
            "Violent storm",
            "Hurricane",
        ],
    },
    # ----------------------------------------------------------------- planes
    {
        "name": "cities_europe",
        "family": "plane",
        "expected": "2D map plane",
        "values": [
            "Lisbon",
            "Madrid",
            "Paris",
            "London",
            "Dublin",
            "Amsterdam",
            "Berlin",
            "Copenhagen",
            "Stockholm",
            "Warsaw",
            "Vienna",
            "Rome",
        ],
    },
    {
        "name": "cities_asia",
        "family": "plane",
        "expected": "2D map plane",
        "values": [
            "Istanbul",
            "Tehran",
            "Karachi",
            "Delhi",
            "Colombo",
            "Dhaka",
            "Bangkok",
            "Singapore",
            "Jakarta",
            "Manila",
            "Shanghai",
            "Seoul",
        ],
    },
    {
        "name": "cities_south_america",
        "family": "plane",
        "expected": "2D map plane",
        "values": [
            "Cartagena",
            "Caracas",
            "Quito",
            "Lima",
            "La Paz",
            "Brasilia",
            "Salvador",
            "Asuncion",
            "Santiago",
            "Cordoba",
            "Montevideo",
            "Ushuaia",
        ],
    },
    {
        "name": "us_states",
        "family": "plane",
        "expected": "2D map plane",
        "values": [
            "Washington",
            "Oregon",
            "California",
            "Nevada",
            "Idaho",
            "Utah",
            "Arizona",
            "Colorado",
            "Texas",
            "Minnesota",
            "Illinois",
            "Georgia",
            "Florida",
            "Virginia",
            "New York",
            "Maine",
        ],
    },
    {
        "name": "ipa_consonants",
        "family": "plane",
        "expected": "place-by-manner plane (2D)",
        "values": ["p", "b", "t", "d", "k", "g", "f", "v", "s", "z", "m", "n"],
    },
    {
        "name": "keyboard_letters",
        "family": "plane",
        "expected": "QWERTY layout plane (2D)",
        "values": ["Q", "W", "E", "R", "T", "A", "S", "D", "F", "G"],
    },
    # ---------------------------------------------------------------- spheres
    {
        "name": "world_capitals",
        "family": "sphere",
        "expected": "2D sphere (S2)",
        "values": [
            "Reykjavik",
            "Ottawa",
            "Mexico City",
            "Bogota",
            "Santiago",
            "Dakar",
            "Lagos",
            "Nairobi",
            "Pretoria",
            "Riyadh",
            "Astana",
            "Ulaanbaatar",
            "Hanoi",
            "Canberra",
            "Wellington",
            "Suva",
        ],
    },
    {
        "name": "airports_global",
        "family": "sphere",
        "expected": "2D sphere (S2)",
        "values": [
            "LAX",
            "JFK",
            "GRU",
            "LHR",
            "CDG",
            "FRA",
            "JNB",
            "DXB",
            "DEL",
            "HKG",
            "NRT",
            "SYD",
        ],
    },
    # ------------------------------------------------------------------ trees
    {
        "name": "language_families",
        "family": "tree",
        "expected": "tree (H0, no loops)",
        "values": [
            "language",
            "Indo-European",
            "Germanic",
            "English",
            "German",
            "Dutch",
            "Romance",
            "French",
            "Spanish",
            "Italian",
            "Slavic",
            "Russian",
            "Polish",
            "Sino-Tibetan",
            "Mandarin",
            "Tibetan",
        ],
    },
    {
        "name": "food_taxonomy",
        "family": "tree",
        "expected": "tree (H0, no loops)",
        "values": [
            "food",
            "produce",
            "fruit",
            "citrus",
            "orange",
            "lemon",
            "berry",
            "strawberry",
            "vegetable",
            "root vegetable",
            "carrot",
            "leafy green",
            "spinach",
            "grain",
            "wheat",
            "rice",
        ],
    },
    # ------------------------------------------------------------------ grids
    {
        "name": "go_coordinates",
        "family": "grid",
        "expected": "4x4 grid (2D)",
        "values": [
            "A1",
            "A2",
            "A3",
            "A4",
            "B1",
            "B2",
            "B3",
            "B4",
            "C1",
            "C2",
            "C3",
            "C4",
            "D1",
            "D2",
            "D3",
            "D4",
        ],
    },
    {
        "name": "spreadsheet_cells",
        "family": "grid",
        "expected": "4x4 grid (2D)",
        "values": [
            "cell A1",
            "cell A2",
            "cell A3",
            "cell A4",
            "cell B1",
            "cell B2",
            "cell B3",
            "cell B4",
            "cell C1",
            "cell C2",
            "cell C3",
            "cell C4",
            "cell D1",
            "cell D2",
            "cell D3",
            "cell D4",
        ],
    },
]
